server.port: 7000

auth:
  server:
    base:
      url: http://localhost:8080

jwt:
  signing:
    key: ymLTU8rq83j4fmJZj60wh4OrMNuntIj4fmJ

logging:
  file:
    name: inventory-api.log
server.error.include-message: always

# Strongly recommend to set this property to "none" in a production environment!
spring.jpa.hibernate.ddl-auto: update
spring:
  main:
    allow-circular-references: true
  datasource:
    password:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/test
    username: pc
    driver-class-name: com.mysql.cj.jdbc.Driver
---
spring.config.activate.on-profile: docker

server.port: 7000

spring.datasource:
  url: jdbc:mysql://mysql/inventory-db
  password: pwd
  username: admin


auth.server.base.url: http://authentication:8080
