version: '1.0'

services:

  inventory:
    build: /inventory-server
    mem_limit: 512m
    ports:
      - 7000:7000
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy

  authentication:
    build: /authentication-server
    mem_limit: 512m
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql:
        condition: service_healthy



  mysql:
    image: mysql:8.0.31
    mem_limit: 600m
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=authentication-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=pwd
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60